### ISSUE TITLE
How to deploy the site?

### ISSUE THREAD

**Issue by fraserxu** [btford/briantford.com#5]
Hi, like your blog a lot and thx for sharing so much amazing articles about angularjs.

I'm trying to deploy this site on my own machine but just didn't know how to make it work.

Not sure if it need ruby environment or anything else? plz help or write some simple instruction for deplying it. Thx a lot!

**Comment by btford** [comment]
You need to have Node.js and `compass` installed. See: http://compass-style.org/install/ and http://nodejs.org/

To build the site, run `make`.
